### ISSUE TITLE
0009-Orbital-CVEHuntToServiceNowIncident fails to import

### ISSUE THREAD

**Issue by johnosn** [CiscoSecurity/sxo-05-security-workflows#1]
**Workflow:** 0009-Orbital-CVEHuntToServiceNowIncident
**GIT Version:** Updated description - 64430742
**Description:**
Attempting to import this workflow results in the following error.

> There was a problem importing the workflow:
> 
> Precondition failed - Workflow trying to import is dependent on atomic workflows: ["Orbital - Query All Endpoints"] which are missing. Please make sure all dependent atomic workflows exists in the system then try again.

There is no Atomic in this or the default repository called "Orbital - Query All Endpoints".

**Comment by mavander** [comment]
Hi @johnosn -

That atomic action is actually in the default repository configured out of the box in orchestration. Try these steps:
1. Go to your Workflows page
2. Click the Import button
3. Select the `GitHub_Target_Atomics` repository
4. Select `OrbitalQueryEndpoint` for the File Name
5. Select the latest version
6. Click Import

Once the atomic is imported, try importing the CVE hunt workflow again.

-Matt

**Comment by johnosn** [comment]
"ORBITAL - QUERY ENDPOINT" has been installed for sometime in my environment.
**GIT VERSION:** Querying a single endpoint -6/29/2020, 3:11:22 AM
I have reloaded this Atomic twice today using the version listed above (as it is the most recent one listed) and it does show as "Validated". However, I continue to get the same error message when attempting to import the workflow.

> There was a problem importing the workflow:
> 
> Precondition failed - Workflow trying to import is dependent on atomic workflows: ["Orbital - Query All Endpoints"] which are missing. Please make sure all dependent atomic workflows exists in the system then try again.

This happen when attempting to directly load from github or if I try to paste the JSON into the Import Workflow.

**Comment by mavander** [comment]
Hi @johnosn -

Sorry, I misread your first message. You're correct, that atomic wasn't published. I've published it in this repository, so if you have a target for this repo's atomics folder, you should now see `Orbital-QueryAllEndpoints`. Note that this atomic is experimental due to some limitations with the Orbital API. Documentation on configuring this repo in orchestration can be found [here](https://ciscosecurity.github.io/sxo-05-security-workflows/configuration).

Try importing that atomic and then try importing the workflow again.

-Matt

**Comment by johnosn** [comment]
Thanks @mavander 
Now that the Orbital Atomic is available I am able to pull in the workflow.
