### ISSUE TITLE
System Atomic: "Secure Malware Analytics - Submit URL" - Request Additional Output from Atomic 

### ISSUE THREAD

**Issue by cin101** [CiscoSecurity/sxo-05-security-workflows#124]
When a URL is submitted to Secure Malware Analytics using the Atomic and "Wait for Results" is set to "False" the only output that is set from the Atomic is "Sample ID" which is the Submission ID. The underlying API response contains additional key:values as documented at [https://panacea.threatgrid.com/mask/api-doc/api/v2/samples]

Contrast this to the behavior of "Secure Malware Analytics - Submit File" Atomics when "Wait for Results" is set to "False" two outputs variables are set "Sample ID" and "Sample Details". "Sample Details" contains the raw JSON response data, which I can JSONPATH query other key:values from.  In my use case, when I submit a URL to Secure Malware Analytics I want the Sample ID and the sha256 of the URL at submission time to be used for other workflow activities while the Analysis is being executed. 

I would like to see the behavior in regards to the Submit URL and Submit File when "Wait for Results" is set to "False" be the same. I don't believe that this would be a breaking change to update the Output Variable of "Secure Malware Analytics - Submit URL" "Sample Details" at submission time.
 
Reviewing the atomic, it looks like the Output Variable already exists in the Atomic Workflow, but is not updated by the Atomic at all during any execution paths that I could see.

**Comment by mavander** [comment]
Hello!
I've made this change in the "Secure Malware Analytics - Submit URL" atomic. The full JSON response from Secure Malware Analytics will be in the `Sample Details` output variable now, even if `Wait for Results` is `False`. Since this atomic is a system object, you won't see the change until the next SecureX orchestration release around January 19th. Thanks for the suggestions!
-Matt
