### ISSUE TITLE
Unable to output observables 

### ISSUE THREAD

**Issue by verlenedodds1** [CiscoSecurity/sxo-05-security-workflows#175]
When I have the final WebEx output it outputs the variables as unknown, here is what it looks like. Is there any known reason why I may be having this problem when processing a .eml file?

<img width="981" alt="image" src="https://user-images.githubusercontent.com/107222251/178495591-cff29f0d-b0ed-4664-a100-245cac04bc57.png">

**Comment by mavander** [comment]
Hello-

This happens if the workflow is unable to locate the following headers in the email: `From`, `Subject`, and `To`. To debug this:
1. Open a previous run of this workflow (one that sent a message like this with `Unknown`)
2. Look for the `Extract information about the email` activity and click on it
3. On the activity properties on the right, look for the input field with the JSON of the email's headers
4. Check which headers are there. Do you see `From`, `Subject`, or `To`? Are the headers in a different language?

Let me know what you find.

-Matt

**Comment by verlenedodds1** [comment]
That activity does not actually show within the orchestration, here is a screenshot of the majority of it.
<img width="478" alt="Screen Shot 2022-07-26 at 8 09 40 AM" src="https://user-images.githubusercontent.com/107222251/181026888-8ed6cf50-2814-41b6-bb6a-bf1f0ff9d080.png">

**Comment by mavander** [comment]
Strange, that could be a bug in the user interface. Have you tried clicking where it says "1 of 1" on the loops and selecting the Instance 1 option in the drop down? Whatever executed in the loop should be visible. If you're not able to figure it out, you'll need to contact Cisco TAC. We only support workflow issues through GitHub, but it you're struggling with the product itself you'll need to get in touch with TAC.

-Matt
