### ISSUE TITLE
0024 - Secure Firewall - Incident Endpoint Enrichment Run

### ISSUE THREAD

**Issue by aledipas** [CiscoSecurity/sxo-05-security-workflows#209]
Hi All,

Just recently starting hitting an issue with this workflow in automation this weekend. It appears that there is an issue, possibly due to the volume of data in our org that our JWT is hitting the 10 minute expiration and causing the workflow run to fail:
![image](https://user-images.githubusercontent.com/77990864/197555333-600360af-6fa7-460b-93ee-8cda4115a086.png)

Status code: 401
Response body: {"error":"invalid_jwt","error_description":"(965bdade-61fd-4e74-ab29-73192113c686) This JWT max lifetime has expired since 1s"}

This is the error message when clicking on the errored "for each incident" block.

I've also had this workflow modified to only search for incidents generated in the past 1 day instead of 7 days. There are also other 400 errors that I haven't been able to diagnose yet but let me know what other data I can pull for this investigation.

Thanks

**Comment by mavander** [comment]
Hello-
The newest version of this workflow is designed to use SecureX Tokens which automatically refresh when they expire. If you're using an old version of the workflow that still has `Threat Response - Generate Access Token`, you'll need to store the token and its expiration time in local variables and then refresh the token if the expiration gets close. We used to do this in a few of our workflows, but don't anymore since everything has been converted to use SecureX Tokens. More information about SecureX Tokens can be found [here](https://ciscosecurity.github.io/sxo-05-security-workflows/account-keys/securex-token).
-Matt
