### ISSUE TITLE
0001 - Talos - Get New Blog Posts Run

### ISSUE THREAD

**Issue by aledipas** [CiscoSecurity/sxo-05-security-workflows#233]
After two new Talos blogs were posted on the 14th, we began seeing a variable too large error in this workflow. I've verified that the workflow is unmodified and using the latest available version in SecureX Test:

`023NSXZ697WVH0udbZprjrkWJyXKExP5SiZ, error: Variable 021G26RD6LF322q3JcnGmS89u4nevHqYfi4 size limit reached: size must be <= 1048576 bytes, but got 1315650 bytes`

`{
  "output": {
    "error": {
      "code": "400",
      "message": "id: 023NSXZ5GRFP46jEb1zWSATpdAvJjdkUse7, wf_instance_id: 023NSWNP6YXH97bIYq5YCVC7CwxOvXkYhgR, error: id: 023NSXZ697WVH0udbZprjrkWJyXKExP5SiZ, wf_instance_id: 023NSWNP6YXH97bIYq5YCVC7CwxOvXkYhgR, error: id: 023NSYI2G0D4E6jJoyjDxo76Hfi3X0A8y5e, wf_instance_id: 023NSXZ697WVH0udbZprjrkWJyXKExP5SiZ, error: id: 023NSZWROFJ410iP2K1cxu6wZOPv8K2irNJ, wf_instance_id: 023NSXZ697WVH0udbZprjrkWJyXKExP5SiZ, error: id: 023NSZWSR7LNU6CsBHe44JISnwizGS9K3oC, wf_instance_id: 023NSXZ697WVH0udbZprjrkWJyXKExP5SiZ, error: id: 023NT0AA5LJ2Y52tNH5hsgh78Qlewz3rqHr, wf_instance_id: 023NSXZ697WVH0udbZprjrkWJyXKExP5SiZ, error: id: 023NT0AAWZ8TX0bdQpyFKydwbwL1uW3k3KR, wf_instance_id: 023NSXZ697WVH0udbZprjrkWJyXKExP5SiZ, error: Variable 021G26RD6LF322q3JcnGmS89u4nevHqYfi4 size limit reached: size must be <= 1048576 bytes, but got 1315650 bytes"
    },
    "response": {
      "elapsed_time": 284.37898687,
      "end_time": "2023-02-17T10:26:37.562Z",
      "start_time": "2023-02-17T10:21:53.183Z",
      "succeeded": false
    }
  }
}`

![image](https://user-images.githubusercontent.com/77990864/219695312-6ea4d266-9272-45b9-ab1d-d6ebdba8306a.png)

**Comment by maimahes** [comment]
Noticed enhancement request by SecureX escalations team on this..any plans on increasing the variable size limit ? please ping me if you need the cdets bug ID or the SR number

**Comment by mavander** [comment]
Hello-

@aledipas - This is a product limitation. We can't do anything about this size limit and since the content is variable in size at runtime it's difficult for us to break it up. The only thing we could do is move more of the workflow's logic into Python but that comes with its own limitations/issues. This workflow is going to be deprecated/replaced in the next few months with Cisco XDR coming (because XDR has some functionality built in to use Talos intelligence that kind of makes this workflow unnecessary in some cases).

@maimahes - This is an engineering question which I can't answer in a public forum like Github. You may wish to follow up on the CDETS internally, but I can't comment on it here.

-Matt
