### ISSUE TITLE
0031 - Secure Firewall - Microsoft Online Dynamic Object Update Run Erroring with json decoding

### ISSUE THREAD

**Issue by carsmit2** [CiscoSecurity/sxo-05-security-workflows#245]
Running the work flow 0031 - Secure Firewall - Microsoft Online Dynamic Object Update Run is failing about every other run currently. The issue observed is at the step of "Get and parse JSON from Microsoft" each time it happens with a 400 error message.

![WF-0031_error1](https://github.com/CiscoSecurity/sxo-05-security-workflows/assets/127149455/59e18283-ce56-458e-a4f4-78b0de4077d7)

With the error displayed:
{
  "output": {
    "error": {
      "code": "400",
      "message": "action execution  errored for type python3.script err:code:400 message::Error:     raise JSONDecodeError(\"Expecting value\", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"
    },
    "response": {
      "elapsed_time": 127.062928424,
      "end_time": "2023-05-13T10:32:58.644Z",
      "start_time": "2023-05-13T10:30:51.581Z",
      "succeeded": false
    }
  }
}

The error message point to there being an issues with parsing json string. Trying to make the same Microsoft API request that is used in the workflow will occasionally time out with 503. 

![accbc9ea-5570-41d7-a9c3-d8613f934180](https://github.com/CiscoSecurity/sxo-05-security-workflows/assets/127149455/e65ed191-298b-4540-9342-78e907799cd4)

**Comment by mavander** [comment]
Hello!

This isn't an issue with the workflow, it's a problem with the Microsoft API returning a 503. The workflow considers a 503 a failure since no network information was returned and fails. This is the correct behavior. If you want to address why Microsoft is returning a 503, you would need to contact them and ask why their service is intermittently returning an error.

-Matt
