### ISSUE TITLE
0010 - Phishing Investigation workflow IMAP gives "Bad request - Target validation errored: LOGIN failed."

### ISSUE THREAD

**Issue by gpadimanskas** [CiscoSecurity/sxo-05-security-workflows#254]
Hi, 
As stated in topic I  have issues with "0010 - Phishing Investigation" workflow.
I have setup Target (IMAP Endpoint type) for Phishing Mailbox Trigger however get "Bad request - Target validation errored: LOGIN failed.".

After reading for similar issue I found it most likely related to Microsoft disabling Basic authentication:
https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#re-enabling-and-opting-out-of-proactive-protection 

As workaround tried to utilize Graph API ( for interacting with MS mailboxes) and created webhook in Securex for pushing Graph API subscription notifications when new email received, however apparently Graph API notification subscription requires webhook endpoint to reply with 200 (OK) and Securex webhooks replies with 202(Accepted) only, so subscription fails. I guess I could create web server to forward MS Graph API notifications to Securex but seems excessive to me.

Also current Graph API integration seems to work only with security suite in Azure, no email integration.

Is there plans to adjust Phishing workflow to use Graph API for querying mailboxes as IMAP doesnt work or there is a way to get it working?

**Comment by mavander** [comment]
Hello!

Due to the end of life announcement for Cisco SecureX, the content in this repository is not being actively maintained. We may publish updates to workflows if significant bugs are identified but we will not be publishing routine/maintenance updates.

This specific workflow should work with the IMAP Endpoint target or the Microsoft Graph Endpoint target. If you're using Office 365 with modern authentication, try using the Graph target. First, create a [Microsoft Graph Oauth2 account key](https://docs.securex.security.cisco.com/Orchestration-Help/Content/account-keys-oauth-microsoft-graph.html) and then associate it with a [Microsoft Graph Endpoint target](https://docs.securex.security.cisco.com/Orchestration-Help/Content/targets-microsoft-graph-endpoint.html). You can then use this new target in your email trigger, the same as the IMAP Endpoint target was used before.

I know a few colleagues who have made these changes and had success using modern authentication.

-Matt
