### ISSUE TITLE
"Wait For Event" activity hangs after the approval task is acted upon and completed 

### ISSUE THREAD

**Issue by SecOp187** [CiscoSecurity/sxo-05-security-workflows#41]
Hello @mavander

I imported and configured the Talos - SolarWinds with the correct variables and activity properties. When running the workflow, it gets stuck at Wait For Event for hours even after setting an expiration timeout for the Wait For Event activity and approved the task. 
![image](https://user-images.githubusercontent.com/82619023/118880641-efab6080-b8a6-11eb-83a4-f18fed9f5be0.png)
![image](https://user-images.githubusercontent.com/82619023/118881114-8bd56780-b8a7-11eb-9557-36f062d0dd8e.png)

I also tried the Approval Task and Wait For Event using two workflows but I couldn't still get past the Wait For Event activity.
![image](https://user-images.githubusercontent.com/82619023/118880826-2bdec100-b8a7-11eb-83db-d210b9774f4f.png)
Finally, I used your Sample - Approval Task workflow and set my only email address I log in to SecureX as the task assignee and the run is still stuck at the Wait For Event activity.
![image](https://user-images.githubusercontent.com/82619023/118881390-e078e280-b8a7-11eb-8531-0fdaa72c9930.png)
![image](https://user-images.githubusercontent.com/82619023/118881431-eec6fe80-b8a7-11eb-94fb-d06f2dcf6bf4.png)

Can you please help me resolved this issue?

Thank you,
Delvain

**Comment by mavander** [comment]
Hi @SecOp187 -

I was not able to reproduce this issue. I imported the sample workflow from this repository and it ran as expected. As soon as I approved the task, the workflow continued. Since you're seeing this issue with multiple workflows, there may be a bug or issue with the orchestrator itself, not the individual workflows. I would encourage you to open a TAC case for further assistance as I cannot provide technical support for the product through Github issues.

-Matt
