### ISSUE TITLE
Phishing Investigation Statistics does not return correct results. 

### ISSUE THREAD

**Issue by adisanka-cisco** [CiscoSecurity/sxo-05-security-workflows#94]
<img width="653" alt="Screen Shot 2021-10-14 at 5 10 22 PM" src="https://user-images.githubusercontent.com/57807175/137396021-1267b131-6fc9-4a74-8cd0-79f2e39e0ae5.png">
<img width="812" alt="Screen Shot 2021-10-14 at 5 10 10 PM" src="https://user-images.githubusercontent.com/57807175/137396025-4948fcd9-ac65-4b6e-9a43-4d5c81fe3f8d.png">

workflow runs successfully but the stats are incorrect. There is no match for the start_time criteria causing no stats to be fetched. All values returned are 0 even though I know I have run multiple emails in the past day.

**Comment by jeiband** [comment]
I guess that explains my results as well.

**Comment by pfiano** [comment]
The issue is with the "Select Row to Report On" based on Select from Table activity, the selection clause base on Time is not working anymore, it stopped working sometime august/september last year. The Select from Table activity is not working anymore using a Time selection criteria, I have also tried with a table and short workflow I created myself.

**Comment by mavander** [comment]
This is due to a bug in SecureX orchestration. Engineering is aware of the issue and is working on a fix. For some users, deleting all of the rows in the statistics table global variable resolves the issue. For others, they have to delete everything related to the phishing workflow (both workflows, global variables, and custom table type) and start over. Since this GitHub is for workflow support, this issue will be closed while engineering works on a fix to the product.
