### ISSUE TITLE
Cannot Export `Threat Response - Create Incident` Atomics

### ISSUE THREAD

**Issue by chandrashekar-cohesity** [CiscoSecurity/sxo-05-security-workflows#98]
The existing atomic to create Incident does not support all fields that can be passed in Incident payload like `external_id`. In order to add that, I wanted to duplicate the existing atomic by exporting it and then reuse it to add other payload objects.

* Can the Threat Response atomics be made public so that others can export it? I did not find it on [SecureX git Atomics](https://github.com/CiscoSecurity/sxo-05-security-workflows/tree/Main/Atomics).

![image](https://user-images.githubusercontent.com/59291994/138940263-6c3e35f1-f80d-42f1-a532-ae31b3e6811a.png)

* Can all the objects supported by SecureX Incident payload be added to the existing atomic?

**Comment by mavander** [comment]
Hi-
For this use case, it would be better to just use the `HTTP Request` activity to make the API call to Threat Response (without using an atomic action). When people have a specific use case or need specific API options, it's usually easier to just make the API call yourself. Updating the existing `Threat Response - Create Incident` atomic would take 2-3 weeks due to how system objects are managed. To help you copy how the existing atomic works, I've attached a copy of its JSON for you. Simply replicate how the API call is being made with the access token and you should be able to use any fields/options you want.
-Matt

[definition_workflow_01PP773PI1X3Y1YQWhirIL8Uy40Thd6ND7r.txt](https://github.com/CiscoSecurity/sxo-05-security-workflows/files/7463389/definition_workflow_01PP773PI1X3Y1YQWhirIL8Uy40Thd6ND7r.txt)

**Comment by chandrashekar-cohesity** [comment]
Thanks. I have already created my own Atomic for this one. But I feel that all support API field should be present and they can be made optional. At least in the future.

**Comment by mavander** [comment]
Yes, I agree. These are some of the first atomics we published. With many of our newer atomics, we try to support as much of the API as is reasonably possible. Thanks for your patience and suggestions, we will keep them in mind as we update/create content :)
